### ISSUE TITLE
Assignment-6

### ISSUE THREAD

**Issue by n-grace-henry** [n-grace-henry/Assignment-6#1]
Edited the template .Rmd file to match the criteria given on the assignment page. Made a references.bib file that was downloaded from Zotero that is linked in the YAML and the in-text citations are from this file. Added equations that are shown in the HW description.

**Comment by mdscheuerell** [comment]
This all looks good, Grace, except that you forgot to set the document class to `report` in the YAML:

`documentclass: report`
